### ISSUE TITLE
Поддержать `x-navtitle` и `x-slug` в тегах

### ISSUE THREAD

**Issue by alexeyten** [diplodoc-platform/openapi-extension#50]
Сейчас они по историческим причинам берутся из тегов эндпоинтов.

Предлагаю добавить возможность читать их прямо из описания тега.
```yaml
tags:
- name: Pets
  description: Операции с домашними животными
  x-navtitle: Домашние животные
  x-slug: pets
```
