### ISSUE TITLE
Поддержать x-hidden в тегах и эндпоинтах

### ISSUE THREAD

**Issue by alexeyten** [diplodoc-platform/openapi-extension#51]
Для возможности скрыть теги/эндпоинты из содержания (ToC)

```yaml
tags:
- name: Pets
  description: Операции с домашними животными
  x-hidden: true # не показывать тег в ToC
```

```yaml
path:
  /pets:
    get:
      description: Список домашних животных
      x-hidden: true # не показывать эндпоинт в ToC и на странице тега
      ...
```
